/**************************************************
beginning of licensing agreement
Microsoft Public License (Ms-PL)

This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.

1. Definitions

The terms "reproduce," "reproduction," "derivative works," and "distribution" have the same meaning here as under U.S. copyright law.

A "contribution" is the original software, or any additions or changes to the software.

A "contributor" is any person that distributes its contribution under this license.

"Licensed patents" are a contributor's patent claims that read directly on its contribution.

2. Grant of Rights

(A) Copyright Grant- Subject to the terms of this license, including the license conditions and limitations in section 3, each contributor grants you a non-exclusive, worldwide, royalty-free copyright license to reproduce its contribution, prepare derivative works of its contribution, and distribute its contribution or any derivative works that you create.

(B) Patent Grant- Subject to the terms of this license, including the license conditions and limitations in section 3, each contributor grants you a non-exclusive, worldwide, royalty-free license under its licensed patents to make, have made, use, sell, offer for sale, import, and/or otherwise dispose of its contribution in the software or derivative works of the contribution in the software.

3. Conditions and Limitations

(A) No Trademark License- This license does not grant you rights to use any contributors' name, logo, or trademarks.

(B) If you bring a patent claim against any contributor over patents that you claim are infringed by the software, your patent license from such contributor to the software ends automatically.

(C) If you distribute any portion of the software, you must retain all copyright, patent, trademark, and attribution notices that are present in the software.

(D) If you distribute any portion of the software in source code form, you may do so only under this license by including a complete copy of this license with your distribution. If you distribute any portion of the software in compiled or object code form, you may only do so under a license that complies with this license.

(E) The software is licensed "as-is." You bear the risk of using it. The contributors give no express warranties, guarantees or conditions. You may have additional consumer rights under your local laws which this license cannot change. To the extent permitted under your local laws, the contributors exclude the implied warranties of merchantability, fitness for a particular purpose and non-infringement. 
end of licensing agreement
**************************************************/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PssdiagConfig {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PssdiagConfig.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectBlocking.
        /// </summary>
        internal static string CollectBlocking {
            get {
                return ResourceManager.GetString("CollectBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectProfiler.
        /// </summary>
        internal static string CollectBlockingMaxFileSize {
            get {
                return ResourceManager.GetString("CollectBlockingMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectBlockingShutdown.
        /// </summary>
        internal static string CollectBlockingShutdown {
            get {
                return ResourceManager.GetString("CollectBlockingShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectBlockingStartup.
        /// </summary>
        internal static string CollectBlockingStartup {
            get {
                return ResourceManager.GetString("CollectBlockingStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectEventLogs.
        /// </summary>
        internal static string CollectEventLogs {
            get {
                return ResourceManager.GetString("CollectEventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectPerfmon.
        /// </summary>
        internal static string CollectEventLogShutdown {
            get {
                return ResourceManager.GetString("CollectEventLogShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectEventLogsStartup.
        /// </summary>
        internal static string CollectEventLogsStartup {
            get {
                return ResourceManager.GetString("CollectEventLogsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectPerfmon.
        /// </summary>
        internal static string CollectPerfmon {
            get {
                return ResourceManager.GetString("CollectPerfmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectPerfmonShutdown.
        /// </summary>
        internal static string CollectPerfmonShutdown {
            get {
                return ResourceManager.GetString("CollectPerfmonShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectProfiler.
        /// </summary>
        internal static string CollectProfiler {
            get {
                return ResourceManager.GetString("CollectProfiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectBlockingShutdown.
        /// </summary>
        internal static string CollectSqldaigShutdown {
            get {
                return ResourceManager.GetString("CollectSqldaigShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectSqldiagStartup.
        /// </summary>
        internal static string CollectSqldiag {
            get {
                return ResourceManager.GetString("CollectSqldiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectSqldiagStartup.
        /// </summary>
        internal static string CollectSqldiagStartup {
            get {
                return ResourceManager.GetString("CollectSqldiagStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectXEvent.
        /// </summary>
        internal static string CollectXEvent {
            get {
                return ResourceManager.GetString("CollectXEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceName.
        /// </summary>
        internal static string InstanceName {
            get {
                return ResourceManager.GetString("InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MachineName.
        /// </summary>
        internal static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputFolder.
        /// </summary>
        internal static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfmonInterval.
        /// </summary>
        internal static string PerfmonInterval {
            get {
                return ResourceManager.GetString("PerfmonInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfmonMaxFileSize.
        /// </summary>
        internal static string PerfmonMaxFileSize {
            get {
                return ResourceManager.GetString("PerfmonMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilerFileCount.
        /// </summary>
        internal static string ProfilerFileCount {
            get {
                return ResourceManager.GetString("ProfilerFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilerMaxFileSize.
        /// </summary>
        internal static string ProfilerMaxFileSize {
            get {
                return ResourceManager.GetString("ProfilerMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XEventFileCount.
        /// </summary>
        internal static string XEventFileCount {
            get {
                return ResourceManager.GetString("XEventFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XEventMaxFileSize.
        /// </summary>
        internal static string XEventMaxFileSize {
            get {
                return ResourceManager.GetString("XEventMaxFileSize", resourceCulture);
            }
        }
    }
}
